### ISSUE TITLE
Response headers not being displayed for either 200 or other responses

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-ui#1117]
Response headers not being displayed for either 200 or other results, error sample below shows the issue.

In the sample below the ETag header is defined for the parameters and for the 200 and 405 responses, but it's only being show for the parameters.

![image](https://cloud.githubusercontent.com/assets/11635/6979346/e03232c2-d9e2-11e4-9718-b4299c8acc46.png)

```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that response headers are not rendered",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }                       
                    },
                    {
                        "in": "header",
                        "name": "ETag",
                        "description": "Used as caching key for future requests",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        },
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1"
            ],
            "properties": {
                "test1": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by tsz662** [comment]
I've encountered the same problem with 2.1.1 M2 and develop 2.0.

**Comment by webron** [comment]
@mohsen1 - shouldn't this have been resolved with #930?

**Comment by webron** [comment]
@tlbdk, @tsz662  - can you retest with develop_2.0?

**Comment by tsz662** [comment]
Tested with develop_2.0 but no luck. I guess my swagger.json is pretty straightforward and it looks like this.
````javascript
{
    "swagger": "2.0",
    "info": {
        "title": "Swagger demo",
        "description": "Some description here.",
        "version": "1.0.0"
    },
    "host": "localhost:8080",
    "schemes": [
        "http",
        "https"
    ],
    "basePath": "/api",
    "paths": {
        "/contacts": {
            "get": {
                "summary": "Get the Contact list.",
                "description": "Some description",
                "tags": [
                    "Contacts"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Contact"
                            }
                        }
                    },
                    "404": {
                        "description": "No Contacts registered.",
                        "schema": {
                            "$ref": "#/definitions/ErrorInfo"
                        }
                    }
                }
            },
            "post": {
                "summary": "Creates a new Contact.",
                "description": "Returns the URL of the newly created Contact on success.",
                "tags": [
                    "Contacts"
                ],
                "parameters": [
                    {
                        "name": "X-Auth",
                        "in": "header",
                        "description": "Authentication token",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "X-CSRF",
                        "in": "header",
                        "description": "CSRF token",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "contact",
                        "in": "body",
                        "description": "Attributes of the Contact to create.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Contact"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "headers": {
                            "Location": {
                                "description": "URL of the new Contact.",
                                "type": "string"
                            }
                        },
                        "schema": {
                            "$ref": "#/definitions/Contact"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorInfo"
                        }
                    }
                }
            }
        },
....

**Comment by fehguy** [comment]
Please retest from develop_2.0.  We just updated the swagger-js client.  Reopen if still an issue...

**Comment by tsz662** [comment]
Re-tested with the latest develop_2.0 but still no headers rendered for either 2xx or 4xx responses. The Response Class section where successful responses are to be rendered does not seemingly have the place for headers in the first place, and the Response Messages section where other responses are to be rendered does not render headers.

**Comment by webron** [comment]
This is not resolved.

**Comment by tsz662** [comment]
Can you tell us when v2.1.2 wil be released?

**Comment by webron** [comment]
@tsz662 - that's not the right question. The right question is when will this be resolved. The 2.1.2 milestone is an estimate, not a guarantee.

And as always, PRs are welcome.

**Comment by ar-** [comment]
I found a solution for this (old) problem. A comment in swagger UI indicates "getAllResponseHeaders sometimes falsely returns "" for CORS requests". So I found this:

http://stackoverflow.com/questions/14686769/xmlhttp-getresponseheader-not-working-for-cors

So all the headers that you allow with "Access-Control-Allow-Headers" you also have to expose with "Access-Control-Expose-Headers". I my case I'm using RestEasy in JBoss on the server side. I'm also adding a custom header line, that indicates the response time the server needed. So I had this line:

cres.getHeaders().add("Access-Control-Allow-Headers", "origin, content-type, accept, authorization, Response-Time-Millis");

and now I added this line additinally:

cres.getHeaders().add("Access-Control-Expose-Headers", "origin, content-type, accept, authorization, Response-Time-Millis");

does that make sense?

**Comment by ar-** [comment]
Since this is not fixable in Swagger, but still an ugly usability bug, I would suggest, that the solution should be added as a hint to Swagger UI, like this: "The headers here can be incomplete for CORS requests, because ...... you have to ...... Access-Control-Allow-Headers and Access-Control-Expose-Headers ...... ".

**Comment by tsz662** [comment]
Maybe I'm missing something here... I thought the response headers are simply rendered **based on the response header descriptions in the swagger.json** (like in Swagger Editor).  
Are they supposed to be rendered __after successful communication with the server?__ (I mean, based on the actual headers returned by the server?)  

If so, what are the response headers described in the swagger.json used for?

**Comment by webron** [comment]
@tsz662 - documentation. You can also document an operation as returning `Foo` while it actually returns `Bar`. So the documentation would show `Foo`, but we'll still show you whatever the server returns (`Bar` in this case) when you try out the operation.

**Comment by bandtank** [comment]
@webron That makes sense for the Try It Out button, but it should display exactly what's in the json file for the documentation section, right?

I read all of the posts in this issue and all of the related issues shown above, but it's not clear to me if there's a way to work around this until a fix is released. Will I be able to make it work by following a procedure or do I need to wait for the official fix?

**Comment by webron** [comment]
@bandtank - yes, it should display it as part of the documentation, and this is what this feature request is for. I'm not entirely sure if the information is exposed by swagger-js, but it is, you could probably make it work (and submit a PR too in the process ;)).

**Comment by ar-** [comment]
@bandtank Maybe you have overseen it. I have described a workaround/fix in my posting above. You can follow that. And there wont/can't be a fix for Swagger-UI. So you will always have to follow that.

The only thing to add to Swagger-UI is a description of the workaround on the UI.

**Comment by bandtank** [comment]
@ar- I have no idea how to implement your workaround as the details are too sparse. It's not even clear to me if it has anything to do with my problem or if the extra lines go in any of the swagger-ui files.

**Comment by bandtank** [comment]
@ar- Could you please be more specific about how to implement your workaround? Your post is hard to understand.

**Comment by erikvanzijst** [comment]
There's no voting on GitHub, so here's me expressing interest in this getting fixed.

**Comment by JakePeyser** [comment]
+1 to a fix for this. Almost pulled my hair out thinking something was wrong with my JSON...

**Comment by dalbrekt** [comment]
+1

**Comment by gboysko** [comment]
+1

**Comment by srdrucker** [comment]
+1

**Comment by tavantzo** [comment]
+1

**Comment by nicolas-despres** [comment]
+1

**Comment by alexbutucea** [comment]
+1

**Comment by DavidBiesack** [comment]
Has anyone else tried patch commit #1580 ? I tried and it did not work for me, but I may be missing something.

**Comment by fahran** [comment]
+1

**Comment by ccciudatu** [comment]
+1

**Comment by webtran** [comment]
+1

**Comment by barticus** [comment]
+1

**Comment by chenjianjx** [comment]
When can this be fixed?

**Comment by fehguy** [comment]
You can send a pull request or wait for us to--we're getting swagger-js done, then will move on to this issue.

**Comment by alexvayn** [comment]
+1

**Comment by fehguy** [comment]
Digging in, it looks like *all* response headers are not returned from swagger-js.

**Comment by hlubovac** [comment]
v2.1.3; it looks like this is still broken

**Comment by fehguy** [comment]
Please try master

**Comment by DavidBiesack** [comment]
I pulled master* but I do not see the ETag response headers listed for the 200 or other responses from the swagger.json from the OP.

* git log shows latest commit:
85b0f4b 2015-12-16 | added jsonEditor option (HEAD, origin/master, origin/HEAD, master) [Tony Tam]

**Comment by hlubovac** [comment]
@fehguy 

No - sorry - master doesn't have it (just tried the very latest). If it helps, here's a snippet of the swagger-json for which I'm not seeing header-related markup rendered (maybe I'm doing it wrong):

```javascript
"paths":
{
    "/blah":
    {
		"post":
		{
			"responses":
			{
				"201 Created":
				{
					"description": "Successful operation: resource created",
					"schema":
					{
						"$ref": "#/definitions/blah"
					},
					"headers":
					{
						"location":
						{
							"description": "URL-identifier of the created resource",
							"type": "string"
						}
					}
				}
			}
		}
    }
}
```

**Comment by fehguy** [comment]
thanks @DavidBiesack I was misunderstanding the issue.  It's not that the response headers were missing _from an actual call_, it's that the definition of them are not in the UI???

If that's the case then we can address it easily.  Displaying the actual response headers from a live call is a function of the underlying library, and that behavior has changed a bit.

**Comment by DavidBiesack** [comment]
Yes, the UI does not list the declared response headers -- the presentation of the API documentation is incomplete w/o the headers. See the OP.

(of course, we'd still like to see the actual response headers from the live call, but that's separate.)

**Comment by fehguy** [comment]
this has been fixed by https://github.com/bodnia/swagger-ui/commit/2b377bfa9e70ff29a7a1be4ab6743221898a60b3

**Comment by DavidBiesack** [comment]
Thanks - I pulled master and see the ETag header for the 200 response from the OP's swagger.json

**Comment by hlubovac** [comment]
confirmed working also; thank you

**Comment by abonec** [comment]
I can't understand why my headers still not shown in the response headers. I have this part of json defenition.
```
{
   "responses":{
      "200":{
         "description":"successful auth",
         "schema":{
            "$ref":"#/definitions/User"
         },
         "headers":{
            "access-token":{
               "description":"access token for further authenticate",
               "type":"string"
            },
            "client":{
               "description":"client token for further authenticate ",
               "type":"string"
            },
            "token-type":{
               "description":"token type used for authentication (Bearer as default)",
               "type":"string"
            }
         }
      }
   }
}
```
![image](https://cloud.githubusercontent.com/assets/240587/17728731/6997f80a-6469-11e6-8785-d602214e7c73.png)

I have two other headers but not which I specified in the response.

**Comment by webron** [comment]
Which version do you use?

**Comment by abonec** [comment]
I use 2.2.0 from `master` branch in `dist` folder

**Comment by kpradeepkumarreddy** [comment]
how to access the response headers in the generated code.
for adding header to the request, i can say   api.addHeader(String key, String value). 
for getting header from the response, what should i do.

**Comment by songtianyi** [comment]
+1
what the heck?!
Why swagger ui didn't show all the headers which can be seen in web dev tools?

**Comment by DavidBiesack** [comment]
@songtianyi Please note that this issue has been fixed in Swagger UI, in Dec 2015 via d919a5e . If you still see this, please download the most recent Swagger UI.

**Comment by mateuscb** [comment]
Using the latest docker image as of today:

```
        "Id": "sha256:b1572b5bddd81f6609cecd9ef2efc1088003e83ffef48c228598e0adb91cad97",
        "RepoTags": [
            "swaggerapi/swagger-ui:latest"
        ],
        "RepoDigests": [
            "swaggerapi/swagger-ui@sha256:8d7429d18c125c1d5f858d94be0fe3135e33c760f50ab1a3e91182b3b4643e06"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-11-18T07:15:06.076040079Z",
```

I was expecting the headers to be printed out in the UI with the rest of the response, but they are listed as part of the response documentation:

![image](https://user-images.githubusercontent.com/1319157/33097337-0a2d99e6-cec7-11e7-9f5b-0db0bc3aba46.png)

My YAML:
```
      responses:
        '200':
          description: >
            Successfully authenticated.
            The session ID is returned in a cookie named `JSESSIONID`. You need to include this cookie in subsequent requests.
          headers: 
            Set-Cookie:
              schema: 
                type: string
                example: JSESSIONID=user1@super; talk_session=eyJ0ZW5hbnQiOiJzdXBlciJ9; talk_session.sig=tRFjGoyrMBsSi-NM7H7Cw1_ndf4
              description: test
            Accept-Encoding:
              schema:
                type: string
```

Any ideas?

**Comment by webron** [comment]
@mateuscb this ticket is about a completely different version of swagger-ui. Would suggesting filing a new ticket instead.

**Comment by mateuscb** [comment]
@webron OK that makes sense. I thought it would be somewhat related wince 2.2.0 was mentioned in the thread. Will create a new one. Thanks!
