### ISSUE TITLE
Redundant API Requests on "Edge" Build

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-ui#1358]
**note:** I am building swagger on edge releases, so I get the latest code changes on the `develop_2.0` branches in both the swagger-ui and swagger-js projects. 

Recently, I have noticed that the more paths I have defined, the more API requests are made. [This screencast](http://recordit.co/BxIOHMUDJL) shows that an initial, cache-busted call (`useJQuery: true`) to the api is made, followed by a call to a sessions endpoint on the same server (custom code) to retrieve a token to be used for each api call. Strangely, 10 more calls to the api get queued up immediately after the first api call returns a response. The paths don't render at all until all of the calls have resolved.

I cannot figure out why these calls are getting queued up. The custom code for getting session data also include setting some authorizations, but I can't see how that would affect how many calls for the api are made. I have tried setting the `useJQuery` option to both true and false, to no avail. I'm wondering if anyone else is seeing this same behavior?

Let me know what other relevant information I can provide if the above is not enough.

**Comment by Smolations** [comment]
Possibly related to this, it seems that only the last apiKeyAuthorization header that is added is being applied to requests. This is also happening in `master` for me.  =[

**Comment by Smolations** [comment]
Found the cause of this particular issue and posted it in the swagger-js project (https://github.com/swagger-api/swagger-js/issues/489).

**Comment by fehguy** [comment]
Thanks, this is fixed in https://github.com/swagger-api/swagger-js/pull/566

**Comment by lucian303** [comment]
@fehguy: How would I pull those changes into swagger UI? I've updated my swagger-ui package.json's dependency to `"swagger-client": "swagger-api/swagger-js#d1897d7110548f09a79eb30d14b5264a595011a2"` which is the latest master commit, pulled the latest swagger-ui changes from master, but I'm still seeing the same problem. Also got this when running `npm update`:
```
npm WARN unmet dependency /Users/lucian303/Desktop/htdocs/ucf-swagger-ui/node_modules/swagger-client/node_modules/superagent requires cookiejar@'2.0.1' but will load
npm WARN unmet dependency /Users/lucian303/Desktop/htdocs/ucf-swagger-ui/node_modules/swagger-client/node_modules/cookiejar,
npm WARN unmet dependency which is version 2.0.2
```

**Comment by fehguy** [comment]
Hi, the release is done (2.1.3) so no need now.  But in general, if you want to pull in a build of swagger-client built locally (i.e., one that's unpublished), follow these incredibly intuitive steps:

 - In swagger-client, run `npm link`.  This will symlink your local copy of swagger-cllient to your ~/.npm folder

 - In swagger-ui, ensure that your `package.json` points to the right version of swagger-client, then run `npm link swagger-client`, followed by `npm install`.

 - Finally `gulp` will update your local distribution.
