### ISSUE TITLE
Relative references (still) don't work?

### ISSUE THREAD

**Issue by reuzel** [swagger-api/swagger-ui#1456]
Hi,

Question: I see that issue #1093, as well as the issue 417 on swagger.js are marked as closed. But it still does not seem to work for me. Am I doing something wrong? Am I missing some configurations?

The API shows, but the reference is not resolved. It displays an empty model for the reference:

```
Dog {
name (string, optional),
owner (people.yml#/Owner, optional)
}

people.yml#/Owner {
}
```

The following test files were used to get to this result. These three yml files are placed in the root of the swagger-ui directory. Swagger-ui is loaded via http://localhost/swagger/. I've updated index.html accordingly.

dog.yml is the API entry point and contains:
```yaml
swagger: '2.0'

info:
  version: '1'
  title: Reference check

basePath: /api

definitions:
  Dog:
    title: "Dog"
    properties:
      name:
        type: string
      owner:
        $ref: 'people.yml#/Owner'
        
paths:
  /Dogs:
    get:
      summary: Gets an 'A'
      parameters:
        - name: name
          in: query
          type: string
      responses:
        200:
          description: Found!
          schema:
            $ref: '#/definitions/Dog'

```

people.yml contains:
```yaml
Owner:
  title: "A Dog owner"
  properties:
    person:
      $ref: "#/Person"
    since:
      type: string
      format: date-time
      
Person:
  title: "Somebody"
  properties:
    name: 
      type: string
    address:
      $ref: 'address.yml'
```

and finally address.yml contains:
```yaml
Address:
  title: An address
  properties:
    street:
      type: string
    number:
      type: int
```

What do I need to do to make this work? I've tried this with the latest develop_20 version (using the dist folder contents)

**Comment by danielm64** [comment]
Yeah! +1

Our external references will point on full swagger spec, not on yaml fragments as illustrated by @reuzel .
They should/will look like (relative and absolute references):
```
$ref: 'organization/people.yml#/definitions/Owner'
$ref: '/company.yml#/definitions/Boss'
```

**Comment by ralfhandl** [comment]
I encounter a similar problem. All types used in requests and responses are defined in a JSON Schema file, which contains local references to types defined in the same JSON Schema file. The Swagger file references these types in schemas for requests and responses.

Unfortunately only those types that are directly (and absolutely) referenced from the Swagger file are correctly resolved, relative references within the JSON Schema file to types that have not by chance already been directly referenced from the Swagger file are not resolved.

Example: file `ref.json.schema` contains
```JSON
{
	"$schema":"http://json-schema.org/draft-04/schema#",
	"definitions":{
		"Address":{
			"type":"object",
			"properties":{
				"Street":{
					"type":"string"
				},
				"City":{
					"type":"string"
				}
			}
		},
		"Person":{
			"type":"object",
			"properties":{
				"Name":{
					"type":"string"
				},
				"Address":{
					"$ref":"#/definitions/Address"
				}
			}
		}
	}
}
```
This is referenced in `ref.swagger.json`:
```JSON
{
	"swagger":"2.0",
	"info":{
		"title":"People",
		"version":"0.1"
	},
	"host":"localhost",
	"schemes":[
		"http"
	],
	"basePath":"/examples",
	"consumes":[
		"application/json"
	],
	"produces":[
		"application/json"
	],
	"paths":{
		"/People":{
			"get":{
				"responses":{
					"200":{
						"schema":{
							"type":"array",
							"items":{
								"$ref":"http://localhost/examples/ref.schema.json#/definitions/Person"
							}
						}
					}
				}
			}
		}
	}
}
```
Swagger-UI only shows the `Name` property.

Now I add a dummy definition to `ref.swagger.json` that references `Address`:
```JSON
	"definitions":{
		"dummy":{
			"type":"object",
			"properties":{
				"dummy0":{
					"$ref":"http://localhost/examples/ref.schema.json#/definitions/Address"
				}
			}
		}
	},
```
Swagger-UI now shows also the `Address` property with its sub-properties `Street` and `City`.

**Comment by ex-nerd** [comment]
Even more examples are described at https://github.com/mohsen1/multi-file-swagger-example the blog post for which is coming up pretty high in search results for this kind of stuff.

**Comment by glen-84** [comment]
@ex-nerd See https://github.com/apigee-127/swagger-tools/issues/227#issuecomment-127729677 for another option.

**Comment by jasonh-n-austin** [comment]
re: @ex-nerd 's comment

We use a simple nodejs script to 'flatten' the file into a single `swagger.json` (as various libs don't support YAML well either), using the excellent [swagger-parser](https://github.com/BigstickCarpet/swagger-parser) (solid support for dereferencing external files). This eliminates a number of library deficiencies in using separate files across the ecosystem.

``` javascript
#!/usr/bin/env node

var parser = require("swagger-parser");
parser.parse("./swagger/swagger.yaml",
             { strictValidation: true, validateSchema: true },
             function(err, api, metadata) {
               // Plenty of opportunities to inject vendor extensions here, of course
               process.stdout.write(JSON.stringify(api, null, 2));
             });
```

Hope it helps as a short-term fix!

**Comment by glen-84** [comment]
@jasonh-n-austin That is what I described in the comment that I linked to. :wink:

**Comment by ex-nerd** [comment]
Working on an example repo to demonstrate this stuff.  Once stuff shows up, it'll be available at https://github.com/ex-nerd/swagger-example

**Comment by ex-nerd** [comment]
ok, I think I have a demo up and running at https://github.com/ex-nerd/swagger-example -- you can see the `build-via-json-refs.js` script that builds properly, but a `grunt test` which uses Sway does not properly find the refs.

**Comment by jasonh-n-austin** [comment]
@glen-84 great minds think alike! :dancers:

**Comment by fehguy** [comment]
confirmed fixed in master, with v2.1.9 of swagger-js:

![image](https://cloud.githubusercontent.com/assets/249413/11701445/72b816be-9e84-11e5-8116-6b956cedeeb3.png)

**Comment by ChristianRich** [comment]
With Swagger latest version 0.7.5 this still doesn't work.

```
definitions:
    $ref: ../definitions/index.yaml
```

```
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start
```

**Comment by fehguy** [comment]
Well, there is no swagger 0.7.5.  What version of the swagger-ui do you have?  View source on swagger-ui.js...

I'm guessing you're picking up swagger-ui through another project, in which case we just don't know what version you're having trouble with.

**Comment by dtoro** [comment]
Still can't load referenced json files:

`
"paths": {
    "/pets": {
        "$ref": "pets.json"
    }
  }
`

Get "failed url" even though the path is right and i can view the file if i click on the path

**Comment by webron** [comment]
@dtoro which version of swagger-ui are you testing?

**Comment by dtoro** [comment]
@webron Never mind. I figured it out!!  Just had to wrap my referenced file in {}  :)  Thanks for the quick response though :)

**Comment by jgreen82** [comment]
@ex-nerd @jasonh-n-austin 
This is more or less a combinations of your two solutions. It works with circular `$ref` dependencies and outputs to yaml (though you can easily add `JSON.stringify()` for json output).

The key was using the [`bundle`](https://github.com/BigstickCarpet/swagger-parser/blob/releases/4.0.0/docs/swagger-parser.md#bundleapi-options-callback) method from `swagger-parser`.
> Bundles all referenced files/URLs into a single api that only has internal $ref pointers.

```
const YAML = require('yaml-js');
const SwaggerParser = require('swagger-parser');
const fs = require('fs');

const swaggerDir = './api/swagger';
const swaggerIndex = `${swaggerDir}/index.yaml`;

SwaggerParser.bundle(swaggerIndex,
  { strictValidation: true, validateSchema: true },
  (err, api, metadata) => {
    console.error(err);
    console.log(YAML.dump(api));
    fs.writeFile(`${swaggerDir}/swagger.yaml`, YAML.dump(api), console.error);
  });
```
Hope this helps someone!

**Comment by francescobianco** [comment]
@reuzel @danielm64 @ex-nerd I suggest you use a command-line tool to build a composed YAML file from a set of included files, use $include tag of https://github.com/javanile/yamlinc 
Is better to have ONE swagger file BUT you can split with your independent tool.
