### ISSUE TITLE
Try it out requires host property & NoHostWarning not shown

### ISSUE THREAD

**Issue by Deraen** [swagger-api/swagger-ui#2760]
I see that the "Try it out" button is supposed to only be shown if the Spec has host property: https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/allow-try-it-out-if-host.js

Why is this? Previously Swagger-UI just presumed that is host is not set, the host serving documentation is used, like described in the Specification: 

https://github.com/OAI/OpenAPI-Specification/blob/master//versions/2.0.md#fixed-fields

>  If the host is not included, the host serving the documentation is to be used (including the port).

Also, if host property is not set, `NoHostWarning` should be shown? I don't see this anywhere.

**Comment by fehguy** [comment]
Seems like a bug, not an intended change

**Comment by shockey** [comment]
Yep, that plugin was proof of a concept, wasn't intended to make it into the open-source release.

Fixed in 3be5d2c.

**Comment by shockey** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.3.

**Comment by larshp** [comment]
Hi,
The "Try it out" button is now shown, however it looks like it just uses the empty value for the host parameter when clicking execute,

`curl -X GET http:///sap/zabapgitserver/rest/list -H  "accept: application/json" -H  "content-type: application/json"`

**Comment by webron** [comment]
@larshp - Do you see that in the actual call the browser makes, or just the generated curl command?

**Comment by larshp** [comment]
also the actual call,
![image](https://cloud.githubusercontent.com/assets/5888506/24389572/e603c0b8-1382-11e7-94c5-9fac95a9424c.png)

did a bit of debugging yesterday, looks like in https://github.com/swagger-api/swagger-js/blob/master/src/execute.js#L178 the contextUrl is "/sap/ztodo/rest/swagger.json" in this example, my guess is that swagger-ui should send the current host as part of the contextUrl?

**Comment by GJRTimmer** [comment]
I have the same problem with the latest version checkout from git.

Exactly the same as above screenshot. Do you need me to post my screenshot?

**Comment by webron** [comment]
@GJRTimmer thanks, I think we've got this covered.

**Comment by GJRTimmer** [comment]
Oke. I hope it is fixed soon. Don't yet know how to fix it myself yet.
Really need swagger-ui to work without a host in the spec and use the
current host and scheme.

Op wo 29 mrt. 2017 19:00 schreef Ron <notifications@github.com>:

**Comment by steinsag** [comment]
Looks like a perfect example for test automation. There are many combinations of basePath, host, schemes, and trailing slashes, etc. May I kindly suggest this gets covered as the Try out feature is one of the coolest Swagger features?

**Comment by webron** [comment]
Based on https://github.com/swagger-api/swagger-js/issues/1000.

@steinsag Agreed. PRs are welcome :)

**Comment by webron** [comment]
All related issues should be fixed with the current master (and latest release). Please report otherwise.

**Comment by Bert-R** [comment]
It is fixed: now "Try it out" works when the spec doesn't contain a host, when the spec is served from the host serving Swagger UI.

There is a remaining issue however: The curl command shows a wrong URL: without host.

**Comment by webron** [comment]
@Bert-R it you see that with the latest master, please file a new ticket. It'll take us a bit to get that fixed though, so PRs would be appreciated.

**Comment by Bert-R** [comment]
It's on the 3.0.5, which is pretty much identical to the latest master.
Once our upgrade passed review and is rolled out, I'll create another ticket.

I understand the pressure on the team, but unfortunately can't make a PR for you as I'm not a front end developer. The issue isn't very urgent, as the "Try it out" functionality works. It's just a matter of misinforming and perhaps confusing the user.

**Comment by steinsag** [comment]
Still not working, will file a new issue :-(

@webron I wasn't able to figure out where in the code path creation is implemented. I'm not familiar with React stuff. So if you give me some pointers, I can take a look. Are there already some tests for this functionality, which could be get extended? I only saw a test for the curl output.
