### ISSUE TITLE
Bad schema rendering for primitive values in OAS 3.0

### ISSUE THREAD

**Issue by LMnet** [swagger-api/swagger-ui#3500]
For OAS 3.0 rendering of primitive values (not object or array) in the schema somehow broken:
1. The schema doesn't have a name.
2. Any usages of the schema with the primitive value inside another schema leaves blank space.

Rendering screenshot: http://imgur.com/IJdpWlk

Reproducible for both swagger-editor and standalone swagger-ui.

Swagger version:
```json
{
  "swaggerEditor": "3.1.0/g66e6130-dirty",
  "swaggerUi": {
    "buildTimestamp": "Sat, 29 Jul 2017 19:20:17 GMT",
    "gitDirty": false,
    "gitRevision": "g0f7fa1f",
    "machine": "testing-gce-6bc5f0a0-dfd8-49cf-a163-82f7473df464",
    "version": "3.1.0"
  }
}
```

Minimal reproducible config:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test
paths:
  /test:
    get:
      responses:
        200:
          description: test
components:
  schemas:
    primitive:
      type: integer
      format: int64
    array-of-primitives:
      type: array
      items: 
        - $ref: '#/components/schemas/primitive'
      default: [1]
```

**Comment by hkosova** [comment]
> Any usages of the schema with the primitive value inside another schema leaves blank space.

This is because the spec is not valid. It should be
```
      items: 
         $ref: '#/components/schemas/primitive'
```
without the `-` before `$ref`. `items` is an object, not an array.

Also, OAS 3.0 says the response status codes must be quoted: `'200'`

**Comment by LMnet** [comment]
I tried your fixes in the swagger editor. Array rendering is fixed. But, primitive value still doesn't have a name and I got this errors in the editor:
```
Schema error at components.schemas['array-of-primitives']
should have required property '$ref'
missingProperty: $ref
Jump to line 16
Schema error at components.schemas['array-of-primitives']
should match exactly one schema in oneOf
Jump to line 16
Schema error at components.schemas['array-of-primitives'].items
should be array
Jump to line 18
```

**Comment by webron** [comment]
@owenconti - I think you dealt with a similar issue before.

**Comment by shockey** [comment]
@LMnet, `items should be an array` was a bug (https://github.com/swagger-api/swagger-editor/issues/1439) that was just fixed (in https://github.com/swagger-api/swagger-editor/pull/1449). Apologies for the misleading error message!

**Comment by LMnet** [comment]
@shockey :+1: 
But rendering primitives without a name is still here.

**Comment by owenconti** [comment]
@LMnet working on it now.

**Comment by iget-master** [comment]
I'm using the swagger editor online (http://editor.swagger.io/) and still have the same issue:

```
openapi: "3.0.0"
info:
  title: api
  version: "1.0.0"
paths:
  /tenant:
    get:
      tags: ["Tenant"]
      responses:
        200:
          description: A list of Tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/tenant"
components:
  schemas:
    tenant:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        name:
          type: string
        owner_user_id:
          type: integer
```

This causes a lot of errors:

```
Schema error at paths['/tenant'].get.responses['200']
should have required property '$ref'
missingProperty: $ref
Jump to line 10
Schema error at paths['/tenant'].get.responses['200']
should match exactly one schema in oneOf
Jump to line 10
Schema error at paths['/tenant'].get.responses['200'].content['application/json']
should have required property 'examples'
missingProperty: examples
Jump to line 13
Schema error at paths['/tenant'].get.responses['200'].content['application/json']
should match exactly one schema in oneOf
Jump to line 13
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema
should have required property '$ref'
missingProperty: $ref
Jump to line 14
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema
should match exactly one schema in oneOf
Jump to line 14
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema
should have required property '$ref'
missingProperty: $ref
Jump to line 14
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema
should match exactly one schema in oneOf
Jump to line 14
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema.items
should be array
Jump to line 16
Schema error at paths['/tenant'].get.responses['200'].content['application/json'].schema.items
should be array
Jump to line 16
```

If I add the dash before $ref, it works.

**Comment by SoundBlaster** [comment]
@iget-master I found what when I add `$ref` field to my definition with self pointed value this error
```
should have required property '$ref'
missingProperty: $ref
``` 
error is gone.
For example:
```
Courses:
    $ref: '#/components/schemas/Courses'
```
