### ISSUE TITLE
Cannot import yaml file in Safari 10.1.2

### ISSUE THREAD

**Issue by richarda23** [swagger-api/swagger-ui#3554]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.x
| How did you install Swagger-UI? | git clone 
| Which broswer & version?        | Safari 10.1.2
| Which operating system?         | Mac 10.12.6 Sierra

Loading a Yaml file does not work

- File->Import file
- Choose a .yaml swagger file
- Click 'Import file'
It appears that nothing happens. I would expect the file to load and appear in the editor, as it does on Chrome and Firefox.

Here is the log from the Safari console that appears after clicking 'Import File':
`TypeError - invalid attempt to destructure non-iterable instance

  rethrowCaughtError swagger-editable-bundle.js 37706

 processEventQueue swagger-editable-bundle.js 32804

 r swagger-editable-bundle.js 40151

 handleTopLevel swagger-editable-bundle.js 40151
 o swagger-editable-bundle.js 49192`

As a workaround, I just use Chrome instead, but would prefer to use Safari  as we're developing for Mac users.
![screen shot 2017-08-10 at 09 09 18](https://user-images.githubusercontent.com/22676399/29161212-4a058314-7dad-11e7-9dab-cd0908eab8f0.png)

**Comment by shockey** [comment]
This is a Swagger-Editor issue, not a Swagger-UI issue 😄 We'll keep it here, though.

**Comment by shockey** [comment]
This should be fixed in our release tonight.

Thanks for filing this issue, @richarda23!

**Comment by satish5** [comment]
I'm seeing exactly the same issue today in editor.swagger.io. I tried Chrome, Firefox and Safari. Same result in all of them.

**Comment by shockey** [comment]
@satish5, I just tried on editor.swagger.io in Chrome 60 and Safari 10.1 on macOS Sierra, and was able to upload my file without any issues.

Please open a new issue here: https://github.com/swagger-api/swagger-editor/issues/new

Be sure to follow the template and include the file you're trying to upload along with the error you're seeing in your console, so we can get to the bottom of this.

**Comment by satish5** [comment]
@shockey Thank you for responding back. It was still failing for me on all browsers. I then used the link on top that said "switch back to previous editor". That opened up editor2.swagger.io that seemed to be the older interface and that let me load the file. From that, I just switched back to editor.swagger.io and the editor came up with the file already opened. After that the issue went away.
